# Generated by Django 6.0.2 on 2026-02-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_notion', '0006_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
