# Generated by Django 6.0.2 on 2026-02-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_notion', '0007_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work')], max_length=20),
        ),
    ]
