# Generated by Django 6.0.2 on 2026-02-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_notion', '0009_rename_comment_comment_project_comment_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
