# Generated by Django 6.0.2 on 2026-02-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_notion', '0011_task_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
