# Generated by Django 6.0.2 on 2026-02-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_notion', '0013_project_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='completed',
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
