# Generated by Django 6.0.2 on 2026-02-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_notion', '0014_remove_reminder_completed_reminder_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
