# Generated by Django 6.0.2 on 2026-03-03 17:20

from django.db import migrations


def migrate_task_statuses(apps, schema_editor):
    """Migrate old status values to new choices:
    'Completed' -> 'done', 'In Progress' -> 'in_progress', others -> 'todo'
    """
    Task = apps.get_model('mini_notion', 'Task')

    for task in Task.objects.all():
        if task.status == 'Completed':
            task.status = 'done'
        elif task.status == 'In Progress':
            task.status = 'in_progress'
        elif task.status not in ['todo', 'in_progress', 'done']:
            task.status = 'todo'
        task.save()


def reverse_migrate_task_statuses(apps, schema_editor):
    """Reverse migration (not needed, but good practice)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mini_notion', '0018_remove_project_shared_with_project_members_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_task_statuses, reverse_migrate_task_statuses),
    ]
